{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  annotations:
  {{- if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      proxy_set_header Accept-Encoding "";
  {{- end }}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.n8n.domainName }}
      http:
        paths:
          {{- if eq .Values.n8n.deploymentMode "scale" }}
          - path: /webhook/
            pathType: Prefix
            backend:
              service:
                name: webhook
                port:
                  number: 5678
          - path: /webhook-waiting/
            pathType: Prefix
            backend:
              service:
                name: webhook
                port:
                  number: 5678
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
{{- end }}
