n8n:
  imageTag: latest
  deploymentMode: scale # single or scale
  encryptionKey: change-this
  domainName: instance1.domain.com
  storageSize: 2Gi
  db:
    name: n8n
    user: n8n
    password: change-this
  concurrency: 20

ingress:
  enabled: false
  className: nginx
  annotations: {}
  #
  # Traefik ingress example
  #
  # className: traefik
  # annotations:
  #   traefik.ingress.kubernetes.io/router.entrypoints: websecure
  #   traefik.ingress.kubernetes.io/router.tls: "true"
  #   traefik.ingress.kubernetes.io/router.tls.certresolver: le

resources:
  memoryLimit: 1Gi
